language: python
env:
  - TOXENV=py26-django15
  - TOXENV=py26-django14
  - TOXENV=py26-django13
  - TOXENV=py26-django12
  - TOXENV=py27-django15
  - TOXENV=py27-django14
  - TOXENV=py27-django13
  - TOXENV=py27-django12
install:
  - "pip install tox"
script:
  - "tox"
notifications:
    flowdock: e09cf86a93ace282c4fb4d1c4afe100e
